resolver: lts-16.1

packages:
- .

extra-deps:
- pandoc-citeproc-0.17.0.1
- git: https://github.com/oisdk/hakyll-series
  commit: "abf54b49db5fbc06471af38e2aa7b30c392a52b3"

flags: {}
extra-package-dbs: []
