name: compile

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2  
    - uses: actions/setup-haskell@v1.1
      with:
          stack-version: '2.1.3'
    - run: stack build
