name: compile

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2  

    - uses: haskell/actions/setup@v2
      with:
          stack-version: '2.11.1'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('site.cabal') }}


    - name: Build site
      run: |
        stack build
        stack exec site build

    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
